LDAP packages are missing
When trying to add ldap configurations we get the following error first:

2017-08-15 15:29:20.130 9467 ERROR keystone.common.wsgi     import ldap.filter
2017-08-15 15:29:20.130 9467 ERROR keystone.common.wsgi ImportError: No module named ldap.filter

Fixed by installing python-ldap, then we get the following error:

2017-08-15 15:38:01.892 12591 ERROR keystone.common.wsgi     from keystone.identity.backends.ldap import common as common_ldap
2017-08-15 15:38:01.892 12591 ERROR keystone.common.wsgi   File "/usr/lib/python2.7/dist-packages/keystone/identity/backends/ldap/common.py", line 25, in <module>
2017-08-15 15:38:01.892 12591 ERROR keystone.common.wsgi     import ldappool
2017-08-15 15:38:01.892 12591 ERROR keystone.common.wsgi ImportError: No module named ldappool

fixed by adding python-ldappool

also found error in documentation syntax that was causing this:

local:
    Data failed to compile:
----------
    Rendering SLS 'base:keystone.server' failed: Jinja variable 'dict object' has no attribute 'description'
Change-Id: Iae36e803589ab2f9810d2cfaaf6b15e5a5bd0ee1